### ISSUE TITLE
Not working with WC 3

### ISSUE THREAD

**Issue by michaelrimbach** [75nineteen/order-simulator-woocommerce#3]
Hi 75nineteen,

after activating the plugin the wp-cron.php generated the following fatal error:

Fatal error: Uncaught ArgumentCountError: Too few arguments to function WC_Checkout::create_order(), 0 passed in /var/www/xyz/wp-content/plugins/order-simulator-woocommerce-master/woocommerce-order-simulator.php on line 235 and exactly 1 expected in /var/www/xyz/wp-content/plugins/woocommerce/includes/class-wc-checkout.php:269 Stack trace: #0 /var/www/xyz/wp-content/plugins/order-simulator-woocommerce-master/woocommerce-order-simulator.php(235): WC_Checkout->create_order() #1 /var/www/xyz/wp-content/plugins/order-simulator-woocommerce-master/woocommerce-order-simulator.php(120): WC_Order_Simulator->create_orders() #2 /var/www/xyz/wp-includes/class-wp-hook.php(298): WC_Order_Simulator->create_orders_on_init() #3 /var/www/xyz/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #4 /var/www/xyz/wp-includes/plugin.php(515): WP_Hook->do_action(Array) #5 /var/www/xyz/wp-cron.php(117): do_action_ref_array('wcos_create_ord...', Array) #6 {main} thrown in /var/www/xyz/wp-content/plugins/woocommerce/includes/class-wc-checkout.php on line 269

WP, WC and plugin is the newest version. 

Hope you can fix it! Thanks in advance!

Michael

**Comment by michaelrimbach** [comment]
Fixed: https://github.com/75nineteen/order-simulator-woocommerce/pull/4
